require("orsah.packer")
require("orsah.set")
require("orsah.lsp")
require("orsah.autosave")
require("orsah.cmp")
require("orsah.commands")
require("orsah.remap")
require("orsah.auto-pairs")
require("orsah.noice")
require("orsah.netrw")
require("orsah.alpha")
require("orsah.colorpicker")
require("orsah.none-ls")
require("orsah.lualine")

vim.opt.clipboard = "unnamedplus"
